# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commandpb/command.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='commandpb/command.proto',
  package='Juicy',
  syntax='proto3',
  serialized_pb=_b('\n\x17\x63ommandpb/command.proto\x12\x05Juicy\"\xaa\x01\n\nCommandReq\x12*\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x19.Juicy.CommandReq.Command\x12\x0c\n\x04\x61rg1\x18\x02 \x01(\t\x12\x0c\n\x04\x61rg2\x18\x03 \x01(\t\"T\n\x07\x43ommand\x12\x07\n\x03Set\x10\x00\x12\x07\n\x03Get\x10\x01\x12\x08\n\x04Have\x10\x02\x12\t\n\x05\x45mpty\x10\x03\x12\t\n\x05\x43lear\x10\x04\x12\n\n\x06\x44\x65lete\x10\x05\x12\x0b\n\x07Persist\x10\x06\"I\n\x0b\x43ommandResp\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x0c\n\x04res1\x18\x03 \x01(\x08\x12\x0c\n\x04res2\x18\x04 \x01(\t2B\n\tDBCommand\x12\x35\n\nCommandRPC\x12\x11.Juicy.CommandReq\x1a\x12.Juicy.CommandResp\"\x00\x62\x06proto3')
)



_COMMANDREQ_COMMAND = _descriptor.EnumDescriptor(
  name='Command',
  full_name='Juicy.CommandReq.Command',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Set', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Get', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Have', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Empty', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Clear', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Delete', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Persist', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=121,
  serialized_end=205,
)
_sym_db.RegisterEnumDescriptor(_COMMANDREQ_COMMAND)


_COMMANDREQ = _descriptor.Descriptor(
  name='CommandReq',
  full_name='Juicy.CommandReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='Juicy.CommandReq.command', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arg1', full_name='Juicy.CommandReq.arg1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arg2', full_name='Juicy.CommandReq.arg2', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMMANDREQ_COMMAND,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=205,
)


_COMMANDRESP = _descriptor.Descriptor(
  name='CommandResp',
  full_name='Juicy.CommandResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='Juicy.CommandResp.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='Juicy.CommandResp.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='res1', full_name='Juicy.CommandResp.res1', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='res2', full_name='Juicy.CommandResp.res2', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=280,
)

_COMMANDREQ.fields_by_name['command'].enum_type = _COMMANDREQ_COMMAND
_COMMANDREQ_COMMAND.containing_type = _COMMANDREQ
DESCRIPTOR.message_types_by_name['CommandReq'] = _COMMANDREQ
DESCRIPTOR.message_types_by_name['CommandResp'] = _COMMANDRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommandReq = _reflection.GeneratedProtocolMessageType('CommandReq', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDREQ,
  __module__ = 'commandpb.command_pb2'
  # @@protoc_insertion_point(class_scope:Juicy.CommandReq)
  ))
_sym_db.RegisterMessage(CommandReq)

CommandResp = _reflection.GeneratedProtocolMessageType('CommandResp', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDRESP,
  __module__ = 'commandpb.command_pb2'
  # @@protoc_insertion_point(class_scope:Juicy.CommandResp)
  ))
_sym_db.RegisterMessage(CommandResp)



_DBCOMMAND = _descriptor.ServiceDescriptor(
  name='DBCommand',
  full_name='Juicy.DBCommand',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=282,
  serialized_end=348,
  methods=[
  _descriptor.MethodDescriptor(
    name='CommandRPC',
    full_name='Juicy.DBCommand.CommandRPC',
    index=0,
    containing_service=None,
    input_type=_COMMANDREQ,
    output_type=_COMMANDRESP,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DBCOMMAND)

DESCRIPTOR.services_by_name['DBCommand'] = _DBCOMMAND

# @@protoc_insertion_point(module_scope)
