// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commandpb/command.proto

/*
Package Juicy is a generated protocol buffer package.

It is generated from these files:
	commandpb/command.proto

It has these top-level messages:
	CommandReq
	CommandResp
*/
package Juicy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommandReq_Command int32

const (
	CommandReq_Set     CommandReq_Command = 0
	CommandReq_Get     CommandReq_Command = 1
	CommandReq_Have    CommandReq_Command = 2
	CommandReq_Empty   CommandReq_Command = 3
	CommandReq_Clear   CommandReq_Command = 4
	CommandReq_Delete  CommandReq_Command = 5
	CommandReq_Persist CommandReq_Command = 6
)

var CommandReq_Command_name = map[int32]string{
	0: "Set",
	1: "Get",
	2: "Have",
	3: "Empty",
	4: "Clear",
	5: "Delete",
	6: "Persist",
}
var CommandReq_Command_value = map[string]int32{
	"Set":     0,
	"Get":     1,
	"Have":    2,
	"Empty":   3,
	"Clear":   4,
	"Delete":  5,
	"Persist": 6,
}

func (x CommandReq_Command) String() string {
	return proto.EnumName(CommandReq_Command_name, int32(x))
}
func (CommandReq_Command) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type CommandReq struct {
	Command  CommandReq_Command `protobuf:"varint,1,opt,name=command,enum=Juicy.CommandReq_Command" json:"command,omitempty"`
	Key      string             `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value    string             `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	Filename string             `protobuf:"bytes,4,opt,name=filename" json:"filename,omitempty"`
}

func (m *CommandReq) Reset()                    { *m = CommandReq{} }
func (m *CommandReq) String() string            { return proto.CompactTextString(m) }
func (*CommandReq) ProtoMessage()               {}
func (*CommandReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CommandReq) GetCommand() CommandReq_Command {
	if m != nil {
		return m.Command
	}
	return CommandReq_Set
}

func (m *CommandReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CommandReq) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *CommandReq) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type CommandResp struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Empty   bool   `protobuf:"varint,3,opt,name=empty" json:"empty,omitempty"`
	Have    bool   `protobuf:"varint,4,opt,name=have" json:"have,omitempty"`
	Value   string `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
}

func (m *CommandResp) Reset()                    { *m = CommandResp{} }
func (m *CommandResp) String() string            { return proto.CompactTextString(m) }
func (*CommandResp) ProtoMessage()               {}
func (*CommandResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CommandResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CommandResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CommandResp) GetEmpty() bool {
	if m != nil {
		return m.Empty
	}
	return false
}

func (m *CommandResp) GetHave() bool {
	if m != nil {
		return m.Have
	}
	return false
}

func (m *CommandResp) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*CommandReq)(nil), "Juicy.CommandReq")
	proto.RegisterType((*CommandResp)(nil), "Juicy.CommandResp")
	proto.RegisterEnum("Juicy.CommandReq_Command", CommandReq_Command_name, CommandReq_Command_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DBCommand service

type DBCommandClient interface {
	CommandRPC(ctx context.Context, in *CommandReq, opts ...grpc.CallOption) (*CommandResp, error)
}

type dBCommandClient struct {
	cc *grpc.ClientConn
}

func NewDBCommandClient(cc *grpc.ClientConn) DBCommandClient {
	return &dBCommandClient{cc}
}

func (c *dBCommandClient) CommandRPC(ctx context.Context, in *CommandReq, opts ...grpc.CallOption) (*CommandResp, error) {
	out := new(CommandResp)
	err := grpc.Invoke(ctx, "/Juicy.DBCommand/CommandRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DBCommand service

type DBCommandServer interface {
	CommandRPC(context.Context, *CommandReq) (*CommandResp, error)
}

func RegisterDBCommandServer(s *grpc.Server, srv DBCommandServer) {
	s.RegisterService(&_DBCommand_serviceDesc, srv)
}

func _DBCommand_CommandRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBCommandServer).CommandRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Juicy.DBCommand/CommandRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBCommandServer).CommandRPC(ctx, req.(*CommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DBCommand_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Juicy.DBCommand",
	HandlerType: (*DBCommandServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommandRPC",
			Handler:    _DBCommand_CommandRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commandpb/command.proto",
}

func init() { proto.RegisterFile("commandpb/command.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcf, 0x4e, 0x83, 0x40,
	0x10, 0xc6, 0x4b, 0x81, 0x02, 0xd3, 0xc4, 0xac, 0x13, 0x13, 0xb1, 0xa7, 0x86, 0x53, 0x4f, 0x98,
	0xb4, 0xf1, 0x05, 0x4a, 0x8d, 0xc6, 0x53, 0x83, 0xbe, 0xc0, 0x16, 0xc7, 0x48, 0x84, 0x82, 0xbb,
	0x0b, 0x09, 0x07, 0x9f, 0xd4, 0x97, 0x31, 0x2c, 0xff, 0x8c, 0xde, 0xbe, 0xef, 0x9b, 0x2f, 0x30,
	0xbf, 0x59, 0xb8, 0x4e, 0x8a, 0x3c, 0xe7, 0xe7, 0xd7, 0xf2, 0x74, 0xdb, 0xab, 0xb0, 0x14, 0x85,
	0x2a, 0xd0, 0x7e, 0xaa, 0xd2, 0xa4, 0x09, 0xbe, 0x0d, 0x80, 0xa8, 0x1b, 0xc4, 0xf4, 0x89, 0x3b,
	0x70, 0xfa, 0x9a, 0x6f, 0xac, 0x8d, 0xcd, 0xc5, 0xf6, 0x26, 0xd4, 0xbd, 0x70, 0xea, 0x8c, 0x72,
	0x68, 0x22, 0x03, 0xf3, 0x83, 0x1a, 0x7f, 0xbe, 0x36, 0x36, 0x5e, 0xdc, 0x4a, 0xbc, 0x02, 0xbb,
	0xe6, 0x59, 0x45, 0xbe, 0xa9, 0xb3, 0xce, 0xe0, 0x0a, 0xdc, 0xb7, 0x34, 0xa3, 0x33, 0xcf, 0xc9,
	0xb7, 0xf4, 0x60, 0xf4, 0xc1, 0x0b, 0x38, 0xfd, 0x77, 0xd1, 0x01, 0xf3, 0x99, 0x14, 0x9b, 0xb5,
	0xe2, 0x81, 0x14, 0x33, 0xd0, 0x05, 0xeb, 0x91, 0xd7, 0xc4, 0xe6, 0xe8, 0x81, 0x7d, 0x9f, 0x97,
	0xaa, 0x61, 0x66, 0x2b, 0xa3, 0x8c, 0xb8, 0x60, 0x16, 0x02, 0x2c, 0x0e, 0x94, 0x91, 0x22, 0x66,
	0xe3, 0x12, 0x9c, 0x23, 0x09, 0x99, 0x4a, 0xc5, 0x16, 0xc1, 0x17, 0x2c, 0xc7, 0xc5, 0x65, 0x89,
	0x3e, 0x38, 0xb2, 0x4a, 0x12, 0x92, 0x52, 0xd3, 0xb9, 0xf1, 0x60, 0xdb, 0x85, 0x49, 0x88, 0x42,
	0xf4, 0x10, 0x9d, 0xd1, 0x69, 0xfb, 0x37, 0x8d, 0xe1, 0xc6, 0x9d, 0x41, 0x04, 0xeb, 0x9d, 0xd7,
	0x1d, 0x82, 0x1b, 0x6b, 0x3d, 0x01, 0xdb, 0xbf, 0x80, 0xb7, 0x7b, 0xf0, 0x0e, 0xfb, 0x01, 0xeb,
	0x6e, 0x3a, 0xf4, 0x31, 0xc2, 0xcb, 0x7f, 0x77, 0x5d, 0xe1, 0xdf, 0x48, 0x96, 0xc1, 0xec, 0xb4,
	0xd0, 0xcf, 0xb5, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xa7, 0x6e, 0x6b, 0xc9, 0x01, 0x00,
	0x00,
}
